<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_German</name>
   <tag></tag>
   <elementGuidId>7139ed43-3cec-4862-843a-3dc6bbd44d9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div/c-wiz/div[2]/c-wiz/div[2]/div/div[4]/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vSUSRc > div.qSb8Pe > div.Llmcnf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f7966108-a1dc-471f-94f8-c31361881fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Llmcnf</value>
      <webElementGuid>92a027cd-790b-4d1d-89eb-f45d12de8347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>Lm8Uhb</value>
      <webElementGuid>712e23db-76e9-4946-9bf8-8c0fd81fbfc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>German</value>
      <webElementGuid>88457f80-b277-4946-927a-8495c64d9a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;zQTmif SSPGKf RvYhPd BIdYQ aL9XFd&quot;]/div[@class=&quot;T4LgNb&quot;]/div[@class=&quot;WFnNle&quot;]/c-wiz[@class=&quot;MOkH4e BSw7K iYelWb yF6Zo DNkvFf&quot;]/div[@class=&quot;OlSOob&quot;]/c-wiz[@class=&quot;QsA0jb DNkvFf&quot;]/div[@class=&quot;ccvoYb EjH7wc&quot;]/div[@class=&quot;aCQag&quot;]/c-wiz[@class=&quot;kHGNJd DNkvFf&quot;]/div[2]/c-wiz[@class=&quot;bvzp8c DlHcnf&quot;]/div[@class=&quot;ykTHSe&quot;]/div[@class=&quot;pEyuac X4hZJc i6oIBe&quot;]/div[@class=&quot;dykxn C96yib j33Gae&quot;]/div[@class=&quot;vSUSRc&quot;]/div[@class=&quot;qSb8Pe&quot;]/div[@class=&quot;Llmcnf&quot;]</value>
      <webElementGuid>1f4eb44a-fb1f-4929-b387-56746556a8a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div/c-wiz/div[2]/c-wiz/div[2]/div/div[4]/div/div/div[2]</value>
      <webElementGuid>78ceff97-ecd6-4092-b868-3782b05e4ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zulu'])[2]/following::div[5]</value>
      <webElementGuid>0d9a9d7d-240e-4d01-ad1d-33930c1b5197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yoruba'])[2]/following::div[8]</value>
      <webElementGuid>ee8f4070-f759-4049-ad51-83b901e880c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results'])[1]/preceding::div[1]</value>
      <webElementGuid>2c1d35b3-438e-4941-bde1-26bd4e73064e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='man']/parent::*</value>
      <webElementGuid>daf1396b-9922-4ba6-b685-3ca77541d06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]</value>
      <webElementGuid>a2f3d1cd-c282-47dd-83f1-bf1abbaa3ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'German' or . = 'German')]</value>
      <webElementGuid>927335b9-ca23-4151-a5b1-54f7ee9043e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
