<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_checkhistoryJapanese</name>
   <tag></tag>
   <elementGuidId>e8ea65b7-6cc6-4966-9086-d4137f490e0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div/c-wiz/div[2]/c-wiz/div[2]/div/div[4]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vSUSRc > div.qSb8Pe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>223171ad-7a45-4cb0-9189-a48ba6aaf4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>sgblj</value>
      <webElementGuid>f8170a31-bd0c-404e-b21d-7eb44e0e56fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>07a55b3f-8a6b-43b8-a499-26fad6b14f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qSb8Pe</value>
      <webElementGuid>00674c65-489b-4791-85a3-21baea39b640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-language-code</name>
      <type>Main</type>
      <value>ja</value>
      <webElementGuid>1648e6c1-a7cd-4fd7-857d-6b151cbcfc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>checkhistoryJapanese</value>
      <webElementGuid>d68af24e-7a05-4f52-bdac-c00aa6a616f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;zQTmif SSPGKf RvYhPd BIdYQ aL9XFd&quot;]/div[@class=&quot;T4LgNb&quot;]/div[@class=&quot;WFnNle&quot;]/c-wiz[@class=&quot;MOkH4e BSw7K iYelWb yF6Zo DNkvFf&quot;]/div[@class=&quot;OlSOob&quot;]/c-wiz[@class=&quot;QsA0jb DNkvFf&quot;]/div[@class=&quot;ccvoYb EjH7wc&quot;]/div[@class=&quot;aCQag&quot;]/c-wiz[@class=&quot;kHGNJd DNkvFf&quot;]/div[2]/c-wiz[@class=&quot;bvzp8c DlHcnf&quot;]/div[@class=&quot;ykTHSe&quot;]/div[@class=&quot;pEyuac X4hZJc i6oIBe&quot;]/div[@class=&quot;dykxn C96yib j33Gae&quot;]/div[@class=&quot;vSUSRc&quot;]/div[@class=&quot;qSb8Pe&quot;]</value>
      <webElementGuid>9c4026c3-6e88-48cb-8832-b30e166cc2a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div/c-wiz/div[2]/c-wiz/div[2]/div/div[4]/div/div</value>
      <webElementGuid>21c4528f-861c-4950-81b8-20cd38baf0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zulu'])[2]/following::div[3]</value>
      <webElementGuid>396d30b6-d54a-48bc-9356-e23f17c3071e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yoruba'])[2]/following::div[6]</value>
      <webElementGuid>9f02be92-2804-4e01-979c-db4b01a45dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>1eea85b1-003a-4409-bbd7-39614cd2f311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'checkhistoryJapanese' or . = 'checkhistoryJapanese')]</value>
      <webElementGuid>3309d733-1f09-4adc-abab-1209c079ef13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
