<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Sign in_callout</name>
   <tag></tag>
   <elementGuidId>0c2d88ab-37c0-4b1e-ac0d-2b45d3f5d80a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='callout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;callout&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d0affdb2-3d45-486c-9b55-32d295e1782f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>b86bec0d-2dc9-4639-98e3-527daaa86147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>675bc304-6812-4f3f-a5b4-690a08cb2ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>fb8c8fae-a64f-4c75-9bab-29fa10cef31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>callout</value>
      <webElementGuid>b5d9dfee-4697-46b5-b76b-b382bc77e908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ogs.google.com/widget/callout?prid=19015972&amp;pgid=19015969&amp;puid=745d93edabf388f3&amp;cce=1&amp;dc=1&amp;origin=https%3A%2F%2Ftranslate.google.com&amp;cn=callout&amp;pid=269&amp;spid=51&amp;hl=en</value>
      <webElementGuid>fd866f7b-a7bf-4cbe-b601-54bcf39a243e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gb&quot;)/div[@class=&quot;gb_Ld gb_2d gb_Rd gb_Qd&quot;]/div[@class=&quot;gb_Vd gb_Xa gb_Kd&quot;]/div[2]/iframe[1]</value>
      <webElementGuid>b54e9ab9-35b3-434e-ac7d-a10d28c02b58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='callout']</value>
      <webElementGuid>c0a8ee2b-77e9-4162-9a99-c2487062d1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='gb']/div[2]/div[3]/div[2]/iframe</value>
      <webElementGuid>e2106209-18e4-4644-8ce3-2ebd5cfc024e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>25ebe284-ca77-491e-8c26-b4596f4f9a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'callout' and @src = 'https://ogs.google.com/widget/callout?prid=19015972&amp;pgid=19015969&amp;puid=745d93edabf388f3&amp;cce=1&amp;dc=1&amp;origin=https%3A%2F%2Ftranslate.google.com&amp;cn=callout&amp;pid=269&amp;spid=51&amp;hl=en']</value>
      <webElementGuid>ff02734f-fcdc-4f53-8631-afffc46a9ada</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
