<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Close search_yFQBKb</name>
   <tag></tag>
   <elementGuidId>928bb56d-f419-4d46-b7f1-bd803f5f7915</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ykTHSe > div.pEyuac.X4hZJc > div.fMHXgc.qkH7ie > input.yFQBKb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6a60c7e-5f30-4af6-8597-1b65b906553a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search languages</value>
      <webElementGuid>839bd83e-93e2-40a2-b869-f83dd18d2e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yFQBKb</value>
      <webElementGuid>18acc29d-1ec0-463f-a11c-e1d8f8954aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>input:G0jgYd;</value>
      <webElementGuid>a750feca-36f4-4391-9771-13f260339e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>oA4zhb</value>
      <webElementGuid>e619bfba-e7b6-4629-acf5-d3300e466a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search languages</value>
      <webElementGuid>5bd543d2-f52a-4940-afc2-be6bf7151df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56c6db87-2385-4afc-834b-cb721e9d9b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;zQTmif SSPGKf RvYhPd BIdYQ aL9XFd&quot;]/div[@class=&quot;T4LgNb&quot;]/div[@class=&quot;WFnNle&quot;]/c-wiz[@class=&quot;MOkH4e BSw7K iYelWb yF6Zo DNkvFf&quot;]/div[@class=&quot;OlSOob&quot;]/c-wiz[@class=&quot;QsA0jb DNkvFf&quot;]/div[@class=&quot;ccvoYb EjH7wc&quot;]/div[@class=&quot;aCQag&quot;]/c-wiz[@class=&quot;kHGNJd DNkvFf&quot;]/div[2]/c-wiz[@class=&quot;bvzp8c DlHcnf&quot;]/div[@class=&quot;ykTHSe&quot;]/div[@class=&quot;pEyuac X4hZJc&quot;]/div[@class=&quot;fMHXgc qkH7ie&quot;]/input[@class=&quot;yFQBKb&quot;]</value>
      <webElementGuid>1a9f32b6-4b6d-4436-83ed-6fb26916f32b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>557ba25a-8473-4ebf-81ee-0f70583769b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div/c-wiz/div[2]/c-wiz/div[2]/div/div[2]/input</value>
      <webElementGuid>c8453f68-5a3f-4555-b9f7-5c9ae52cdf75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>b9e5118a-fe24-4519-82fc-ca9ee09e47d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search languages' and @type = 'text']</value>
      <webElementGuid>179d53da-295c-4792-baf7-27c119edd757</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
