<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_English_VfPpkd-YVzG2b</name>
   <tag></tag>
   <elementGuidId>bfe1460b-5941-43c9-b1fa-cc344a32f5cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='i8']/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i8 > span.VfPpkd-YVzG2b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>713d09f8-2cd7-4d03-95a2-49ee0d74f693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VfPpkd-YVzG2b</value>
      <webElementGuid>4b04b291-e369-45c5-a3b2-343670117e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>ksKsZd</value>
      <webElementGuid>d5619eb4-b5ae-4ad6-bb52-7789d47c7d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i8&quot;)/span[@class=&quot;VfPpkd-YVzG2b&quot;]</value>
      <webElementGuid>1fde20e5-e87c-4200-8d11-293e0db12ca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='i8']/span[3]</value>
      <webElementGuid>dd1a9a8f-edaa-4af6-8fe6-b33ac7b0790d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span[3]</value>
      <webElementGuid>d0a86e1a-596e-4d61-86d4-b909fa506e76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
