<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>fdb5c908-29a5-4775-91c8-b77c5b074d20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div[2]/div[3]/c-wiz[2]/div[8]/div/div/span/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.Q4iAWc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>25f471a3-4d5a-4afe-8858-773ef413685a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Q4iAWc</value>
      <webElementGuid>53d98102-2f42-4d9a-9c5b-ae7196278053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>click:qtZ4nf,GFf3ac,tMZCfe; contextmenu:Nqw7Te,QP7LD; mouseout:Nqw7Te; mouseover:qtZ4nf,c2aHje</value>
      <webElementGuid>7e2aeaef-486e-4200-bf95-f6ffee59759d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>W297wb</value>
      <webElementGuid>2a776aa1-e301-4ed2-824c-a86f5255fb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>こんにちは、これはカタロンサポートチームの毛沢東です</value>
      <webElementGuid>ffd63de8-0c7a-4146-8118-08cb5d7beb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;zQTmif SSPGKf RvYhPd BIdYQ aL9XFd&quot;]/div[@class=&quot;T4LgNb&quot;]/div[@class=&quot;WFnNle&quot;]/c-wiz[@class=&quot;MOkH4e BSw7K iYelWb yF6Zo&quot;]/div[@class=&quot;OlSOob&quot;]/c-wiz[@class=&quot;QsA0jb&quot;]/div[@class=&quot;ccvoYb EjH7wc&quot;]/div[@class=&quot;AxqVh&quot;]/div[@class=&quot;OPPzxe&quot;]/c-wiz[@class=&quot;P6w8m BDJ8fb&quot;]/div[@class=&quot;dePhmb&quot;]/div[@class=&quot;eyKpYb&quot;]/div[@class=&quot;J0lOec&quot;]/span[@class=&quot;VIiyi&quot;]/span[@class=&quot;JLqJ4b ChMk0b&quot;]/span[@class=&quot;Q4iAWc&quot;]</value>
      <webElementGuid>29ae4c8b-c82a-44e6-b7ba-aadf4abec3b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div[2]/div[3]/c-wiz[2]/div[8]/div/div/span/span/span</value>
      <webElementGuid>81a2831a-941b-440f-9dac-7e01fa490fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save translation'])[1]/following::span[4]</value>
      <webElementGuid>7a0c595e-eb72-41d9-af9b-e9d3921807a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try again'])[1]/following::span[9]</value>
      <webElementGuid>56079061-c07b-4838-8e45-924b104bbf2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='こんにちは、これはカタロンサポートチームの毛沢東です'])[2]/preceding::span[1]</value>
      <webElementGuid>e15a31d6-38d1-4504-86c6-39615caf963a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello, this is Mao Zedong, the Catalon Support Team'])[1]/preceding::span[1]</value>
      <webElementGuid>e529aa77-e1aa-4538-9fd9-3668a2696f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='こんにちは、これはカタロンサポートチームの毛沢東です']/parent::*</value>
      <webElementGuid>f529086e-23ae-459e-947c-bf18543c604b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/span/span/span</value>
      <webElementGuid>4ba69424-fc35-4e9a-aec6-8bd7ae915bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'こんにちは、これはカタロンサポートチームの毛沢東です' or . = 'こんにちは、これはカタロンサポートチームの毛沢東です')]</value>
      <webElementGuid>4866c981-8b41-4e54-9dfc-6bfa9fc9bf02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
