<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Sign in_callout</name>
   <tag></tag>
   <elementGuidId>d027ca0b-6196-4cc1-ab97-36c500ada959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='callout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;callout&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>cf529e71-ac3c-4fcc-be1d-9840c1829e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>c6519e46-4150-41f2-a396-0ec6a45b9586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>10af9001-4072-4e6c-b4b4-a07af9d92983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>826ec28e-0cb6-4fa0-afdf-4b80e2ca3eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>callout</value>
      <webElementGuid>5cd31e38-75ed-45e9-a2b0-6efee2021bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ogs.google.com/widget/callout?prid=19015972&amp;pgid=19015969&amp;puid=745d93edabf388f3&amp;cce=1&amp;dc=1&amp;origin=https%3A%2F%2Ftranslate.google.com&amp;cn=callout&amp;pid=269&amp;spid=51&amp;hl=en</value>
      <webElementGuid>b3a92391-3ca3-4989-924a-12cbdb6a5009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gb&quot;)/div[@class=&quot;gb_Ld gb_2d gb_Rd gb_Qd&quot;]/div[@class=&quot;gb_Vd gb_Xa gb_Kd&quot;]/div[2]/iframe[1]</value>
      <webElementGuid>d483cc29-ca48-4047-a37d-b9de15d2db0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='callout']</value>
      <webElementGuid>fe9d44c0-51c5-43f4-abed-1cea5f95b735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='gb']/div[2]/div[3]/div[2]/iframe</value>
      <webElementGuid>144ef045-a057-4c84-a1c4-7854336fd71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>426e6db1-9365-422a-ae3f-8eb50b392cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'callout' and @src = 'https://ogs.google.com/widget/callout?prid=19015972&amp;pgid=19015969&amp;puid=745d93edabf388f3&amp;cce=1&amp;dc=1&amp;origin=https%3A%2F%2Ftranslate.google.com&amp;cn=callout&amp;pid=269&amp;spid=51&amp;hl=en']</value>
      <webElementGuid>4143d43b-c4b2-4271-bbc7-ee3384260a8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
