<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_English_VfPpkd-YVzG2b</name>
   <tag></tag>
   <elementGuidId>0ed02c1c-9244-48ef-8372-77d07de366db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='i8']/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i8 > span.VfPpkd-YVzG2b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>768a2ae5-47f0-4c08-b413-4032c5b33d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VfPpkd-YVzG2b</value>
      <webElementGuid>64e26276-5c91-4081-a483-9a23e9c7c751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>ksKsZd</value>
      <webElementGuid>9df81101-c1e4-4760-b090-c79c1ea30f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i8&quot;)/span[@class=&quot;VfPpkd-YVzG2b&quot;]</value>
      <webElementGuid>bd1cc6d0-6441-47fb-bd20-a350e7eb5ff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='i8']/span[3]</value>
      <webElementGuid>24036018-5e29-4a1a-99cf-943e6b81c4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span[3]</value>
      <webElementGuid>4916a4b1-6b68-4bd9-9413-00f1e9c09b4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
