<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ting c</name>
   <tag></tag>
   <elementGuidId>8cd33077-b0b1-46fd-b838-72ae2df8c315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tw-container']/g-expandable-container/div/div/div[7]/g-expandable-container/div/g-expandable-content/span/div/div[2]/div[2]/div[22]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>49be9be4-5ab2-4505-96d8-bf9023b13d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-lliw</value>
      <webElementGuid>eb3f6563-a7ae-44f4-afef-717a10ad4242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ac12d8d8-3dd3-4f24-8ee9-07dfa2e2306c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51be4d9c-5755-408f-8d69-f2857019651d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tiếng Đức</value>
      <webElementGuid>a8e089ea-3326-45e3-85b8-2251a586f57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tw-container&quot;)/g-expandable-container[1]/div[1]/div[1]/div[7]/g-expandable-container[1]/div[1]/g-expandable-content[1]/span[1]/div[@class=&quot;zaokob&quot;]/div[@class=&quot;language-list&quot;]/div[@class=&quot;language_list_languages language_list_tl_list tw-ll-top&quot;]/div[@class=&quot;tw-lliw&quot;]</value>
      <webElementGuid>b49bd8ce-2588-4447-abf1-851862c10682</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tw-container']/g-expandable-container/div/div/div[7]/g-expandable-container/div/g-expandable-content/span/div/div[2]/div[2]/div[22]</value>
      <webElementGuid>f94afb35-c672-4f9b-a57e-8b1266d6d9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiếng Đan Mạch'])[2]/following::div[1]</value>
      <webElementGuid>b8be183c-3333-4eeb-ad73-ee34e11bfe67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiếng Do Thái'])[2]/following::div[4]</value>
      <webElementGuid>7bc4a024-d732-4b0b-a328-c3780fd6f6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiếng Estonia'])[2]/preceding::div[5]</value>
      <webElementGuid>62dc2776-0bae-494e-b559-e00b54263453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[22]</value>
      <webElementGuid>0bf3056e-f43a-4822-9763-f9ca794fe6dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tiếng Đức' or . = 'Tiếng Đức')]</value>
      <webElementGuid>589c01f7-c422-4dc8-9c1c-a099531d872b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
