<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bn dch ca_tl_list-search-box</name>
   <tag></tag>
   <elementGuidId>846e5690-6491-4d61-ae1d-35a539b83f65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tl_list-search-box']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tl_list-search-box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9619b9a4-187b-464c-8135-5d2a760fc94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23103517-c76b-46f9-b0fd-51a8a14a34ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tl_list-search-box</value>
      <webElementGuid>b933b7af-2c69-42f8-b645-f120c76a7911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-lp-search F0azHf</value>
      <webElementGuid>dcef4f92-216c-48ed-82a4-d6832d959ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Dịch sang</value>
      <webElementGuid>eac9bb02-a999-4253-8c51-fa78bfa1c655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tl_list-search-box&quot;)</value>
      <webElementGuid>a1634cc9-1ca7-4d3c-a8b3-a3ca02c209cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tl_list-search-box']</value>
      <webElementGuid>7fcb09f1-3d57-4998-b8e4-b94364a1a01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tw-container']/g-expandable-container/div/div/div[7]/g-expandable-container/div/g-expandable-content/span/div/div[2]/input</value>
      <webElementGuid>75867c92-7403-41cf-8d32-9e57b37d5b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div[2]/input</value>
      <webElementGuid>cfa03090-ecbc-4bb8-a146-cd61f4999920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tl_list-search-box' and @placeholder = 'Dịch sang']</value>
      <webElementGuid>31940a29-0890-41d9-8af5-16fa8126271c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
