<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hello_tl_list-search-box</name>
   <tag></tag>
   <elementGuidId>362b3e77-6fb5-4a38-8663-327240e3b49e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tl_list-search-box']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tl_list-search-box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3efa1bbc-277d-40a1-acbd-0cd9b423bb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c241a6e0-9c9e-47a8-883d-150f22a2f7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tl_list-search-box</value>
      <webElementGuid>f516c063-8088-4406-871c-9ef3fcb775c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-lp-search F0azHf</value>
      <webElementGuid>c7f8fdde-6eb4-4d5c-8e2c-9c77b537be92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Dịch sang</value>
      <webElementGuid>26a13083-86fa-47d2-9b79-7f32a9387561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tl_list-search-box&quot;)</value>
      <webElementGuid>ced33acb-e5e6-48e0-a8ed-3a273a353fae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tl_list-search-box']</value>
      <webElementGuid>29c51cd7-97b0-40c7-971a-a1cce95dd20a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tw-container']/g-expandable-container/div/div/div[7]/g-expandable-container/div/g-expandable-content/span/div/div[2]/input</value>
      <webElementGuid>bdefe3bf-453c-4b53-9d31-3981f8f045aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div[2]/input</value>
      <webElementGuid>caad8764-42b8-4cb5-8154-4bfbd0d5dc1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tl_list-search-box' and @placeholder = 'Dịch sang']</value>
      <webElementGuid>cf5aefbf-f1ea-4959-a793-5eec42dfabc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
