<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hallo, hier ist Mao vom Katalon-Support-Team</name>
   <tag></tag>
   <elementGuidId>375b3a41-81c3-441c-8f3e-e8d67c364401</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//pre[@id='tw-target-text']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tw-target-text > span.Y2IQFc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>06c580b2-9e8e-4088-b344-96bea6bb20c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Y2IQFc</value>
      <webElementGuid>f6a46080-a449-4ff0-a1f7-9d8c5993c664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>de</value>
      <webElementGuid>8b8f8d73-3bf7-4ebe-98d4-7ffbc9971be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hallo, hier ist Mao vom Katalon-Support-Team</value>
      <webElementGuid>0c8c519d-195f-4bb4-9aa7-e65ded763fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tw-target-text&quot;)/span[@class=&quot;Y2IQFc&quot;]</value>
      <webElementGuid>b28b35a9-77a3-48da-ac61-9d36aaef0c2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//pre[@id='tw-target-text']/span</value>
      <webElementGuid>afa3080d-e938-4916-a5aa-5d413cad035d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Học cách phát âm'])[1]/following::span[8]</value>
      <webElementGuid>cedc642e-3f96-45a7-b9a1-c502691e61e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nhập văn bản'])[1]/following::span[18]</value>
      <webElementGuid>ad7cbaaf-b2ea-4c7d-b97e-f88e7b720bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đã xác minh'])[1]/preceding::span[2]</value>
      <webElementGuid>eb7d4034-1ecf-4f49-a9d0-fbada3984ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bản dịch này đã được những người đóng góp trên Google Dịch xác minh'])[1]/preceding::span[4]</value>
      <webElementGuid>839d980f-7705-44aa-8d5a-4257c1028945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hallo, hier ist Mao vom Katalon-Support-Team']/parent::*</value>
      <webElementGuid>ff0a41d4-0294-43f3-8cd4-56319e3eaa36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/pre/span</value>
      <webElementGuid>bd3ecf85-0400-4486-8d5c-b1db46763fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Hallo, hier ist Mao vom Katalon-Support-Team' or . = 'Hallo, hier ist Mao vom Katalon-Support-Team')]</value>
      <webElementGuid>a1e5c8c4-72f9-4a66-ba80-7c585ccccdb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
