<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Nhp vn bn_tw-source-text-ta</name>
   <tag></tag>
   <elementGuidId>3787d2a1-3e9a-4ddf-9827-d2ae5fa42c15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'tw-source-text-ta' and @placeholder = 'Nhập văn bản']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@class='er8xn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tw-source-text-ta</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>889b680c-6fbd-4bce-bd26-390672c05e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-ta tw-text-large q8U8x goog-textarea</value>
      <webElementGuid>69486a2b-ad4c-45d9-8d7e-4652af87f6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>288893b9-a9bb-4b21-ab62-885fefba6b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8f17c8e1-0eb6-487c-b93b-614ade829f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tw-source-text-ta</value>
      <webElementGuid>8ffb92d1-a0ad-4cb9-aeee-00a9920632db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập văn bản</value>
      <webElementGuid>73904985-eccf-4198-aba2-cc6a1b04e4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>focus:LSopwc;blur:zxpHKd;TTVyKc</value>
      <webElementGuid>d474c14d-0f24-4a04-842c-c2265d57854c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>01b8d5b9-36f8-4f1d-a2e8-61536c41727a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2d072c58-c7b9-4a5c-a348-81a5d29e4ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5b12102b-5248-43ad-8524-a16852639a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>2ahUKEwiV9_W5xJj5AhUA7HMBHQMHBvYQsaQCegQIAhAG</value>
      <webElementGuid>c0fa957a-ded1-42f0-bffa-adb06a5d17f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>1191bd05-5072-4ff3-ad5c-e2c418c78e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>78347fb6-2abb-4474-8f16-2161d1be93b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tw-source-text-ta&quot;)</value>
      <webElementGuid>caad79cc-e60a-4eb7-8007-2f052d7c4527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='tw-source-text-ta']</value>
      <webElementGuid>48680805-50db-4f2d-84a5-ccc2103f816a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tw-source-text-container']/textarea</value>
      <webElementGuid>35564ed0-2b76-4f7d-94de-e874a01401b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>95ca4998-d728-4833-8c52-c6d3ea7d53e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'tw-source-text-ta' and @placeholder = 'Nhập văn bản']</value>
      <webElementGuid>46f24d87-e6d1-4639-9880-e73cb23c5d77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
